---
apiVersion: v1
kind: Template
metadata:
  name: rhsm-api-proxy
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: rhsm-api-proxy
  spec:
    envName: ${ENV_NAME}
    webServices:
      public: true
      metrics: true
    dependencies:
    - rbac
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: APP_NAME
          value: ${APP_NAME}
        - name: DB_POOL_SIZE
          value: ${DB_POOL_SIZE}
        - name: RAILS_LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: CLOUD_METER_AVAILABILITY_CHECK_URL
          value: ${CLOUD_METER_API_SCHEME}://${CLOUD_METER_API_HOST}:${CLOUD_METER_SOURCES_API_PORT}${CLOUD_METER_SOURCES_API_AVAILABILITY_CHECK_PATH}
        - name: COST_MANAGEMENT_AVAILABILITY_CHECK_URL
          value: ${KOKU_SOURCES_API_SCHEME}://${KOKU_SOURCES_API_HOST}:${KOKU_SOURCES_API_PORT}${KOKU_SOURCES_API_APP_CHECK_PATH}
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: sources-api-secrets
              key: encryption-key
        - name: PATH_PREFIX
          value: ${PATH_PREFIX}
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: sources-api-secrets
              key: secret-key
        - name: RBAC_URL
          value: ${RBAC_SCHEME}://${RBAC_HOST}:${RBAC_PORT}
        readinessProbe:
          tcpSocket:
            port: public
        livenessProbe:
          httpGet:
            path: /health
            port: public
          initialDelaySeconds: 120
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}

parameters:
- description: Application name to be used in request paths.
  displayName: Application Name
  name: APP_NAME
  value: sources
- description: Scheme of the Cloud Meter API
  displayName: Cloud Meter API Scheme
  name: CLOUD_METER_API_SCHEME
  value: http
- description: Hostname of the Cloud Meter API
  displayName: Cloud Meter API Hostname
  name: CLOUD_METER_API_HOST
  required: true
  value: cloudigrade-api
- name: CLOUD_METER_SOURCES_API_PORT
  value: '8000'
- name: CLOUD_METER_SOURCES_API_AVAILABILITY_CHECK_PATH
  value: /internal/api/cloudigrade/v1/availability_status
- name: CPU_LIMIT
  value: 500m
- name: CPU_REQUEST
  value: 100m
- name: DB_POOL_SIZE
  displayName: Database Pool size
  description: Database pool configuration in DATABASE_URL env
  value: "5"
- name: ENCRYPTION_KEY
  displayName: Encryption Key (Ephemeral)
  required: true
  description: Encryption Key for Passwords
  from: "[a-zA-Z0-9]{43}"
  generate: expression
- description: Clowder ENV
  name: ENV_NAME
  required: true
- description: Image
  name: IMAGE
  value: quay.io/cloudservices/sources-api
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: KOKU_SOURCES_API_SCHEME
  value: http
- description: Hostname of the koku sources API server
  displayName: Koku Sources API Hostname
  name: KOKU_SOURCES_API_HOST
  required: true
  value: koku-sources
- name: KOKU_SOURCES_API_PORT
  value: '8000'
- name: KOKU_SOURCES_API_APP_CHECK_PATH
  value: /api/cost-management/v1/source-status/
- name: LOG_LEVEL
  value: WARN
- name: MEMORY_LIMIT
  value: 1Gi
- name: MEMORY_REQUEST
  value: 500Mi
- description: Prometheus Metrics Port
  displayName: Metrics Port
  name: METRICS_PORT
  value: '9000' # default in ClowdEnvironment CRD
- description: The number of replicas to use for the prometheus deploy
  name: MIN_REPLICAS
  value: '1'
