---
apps:
  http:
    servers:
      proxy:
        logs: {}
        listen:
        - ":{{.AppConfig.PublicPort}}"
        routes:
        - match:
          - path:
            - "/api/rhsm/*"
          handle:
          - handler: rewrite
            strip_path_prefix: "/api/rhsm"
          - handler: rbac
            service_url: http://{{(index .Deps "rbac" "service").Hostname}}:{{(index .Deps "rbac" "service").Port}}/api/rbac/v1
            application: subscriptions
          - handler: reverse_proxy
            upstreams:
            - dial: api.rhsm.redhat.com:443
            transport:
              protocol: http
              tls:
                client_certificate_file: "/etc/pki/tls/certs/enterprise_services/nonprod-itpntautomation.pem"
                client_certificate_key_file: "/etc/pki/tls/certs/enterprise_services/nonprod-itpntautomation.pem"
              response_header_timeout: 60s
        - match:
          - path:
            - "/_proxy/ping"
          handle:
          - handler: static_response
            status_code: 200
            body: "pong"
      metrics:
        listen:
        - ":{{.AppConfig.MetricsPort}}"
        routes:
        - handle:
          - handler: metrics
