---
apps:
  http:
    servers:
      proxy:
        logs: {}
        listen:
        - ":8000"
        routes:
        - match:
          - path:
            - "/api/rhsm/*"
          handle:
          - handler: rewrite
            strip_path_prefix: "/api/rhsm"
          - handler: rbac
            service_url: http://localhost:8001/api/rbac/v1
            application: subscriptions
          - handler: reverse_proxy
            upstreams:
            - dial: api.rhsm.redhat.com:443
            transport:
              protocol: http
              tls:
                client_certificate_file: "/etc/pki/tls/certs/enterprise_services/nonprod-itpntautomation.pem"
                client_certificate_key_file: "/etc/pki/tls/certs/enterprise_services/nonprod-itpntautomation.pem"
              response_header_timeout: 60s
      metrics:
        listen:
        - ":9000"
        routes:
        - handle:
          - handler: metrics