---
apps:
  http:
    servers:
      proxy:
        logs: {}
        listen:
        - ":8000"
        routes:
        - match:
          - path:
            - "/api/rhsm/*"
          handle:
          - handler: rewrite
            strip_path_prefix: "/api/rhsm"
          - handler: rbac
            service_url: http://localhost:8001/api/rbac/v1
            application: subscriptions
          - handler: reverse_proxy
            upstreams:
            - dial: api.rhsm.redhat.com:443
            transport:
              protocol: http
              tls: {}
              response_header_timeout: 60s
        - match:
          - path:
            - "/_proxy/ping"
          handle:
          - handler: static_response
            status_code: 200
            body: "pong"
      metrics:
        listen:
        - ":9000"
        routes:
        - handle:
          - handler: metrics
